### ISSUE TITLE
Prevent main window from closing

### ISSUE THREAD

**Issue by shardul08** [shardul08/Student-DataBase-Management-System#1]
When adding a new record by pressing 'Enter Student Details' button, after the details are added closing the 'Add Student Details' window closes the main window as well.
Would be great if someone could sort it out.

**Comment by WhiteMZ** [comment]
can you show the method that you close the "Add student details" window?

**Comment by edikxl** [comment]
I forked. I'll try to do something.

**Comment by shardul08** [comment]
> can you show the method that you close the "Add student details" window?

currently I am using the following method
```python
self.btnCancel.clicked.connect(QApplication.instance().quit)
```

**Comment by edikxl** [comment]
Whats the login and the password?

**Comment by shardul08** [comment]
> Whats the login and the password?

leave both the fields blank
